### ISSUE TITLE
Add accordian panels to Data Tab (dev site)

### ISSUE THREAD

**Issue by DWRbbrew** [wpears/groundwater#6]
Please add the following datasets to the Data Tab
- Well Data
- Subsidence Data
- Base of Fresh Water

**Comment by wpears** [comment]
[Added](https://github.com/wpears/groundwater/commit/4fcb04be028328c1eda4f6e96d21a4fa82605416). I think the styling could probably be improved on the well data rasters and I am all for removing the polygons. They are slow and really not the best way to display the data, imo.

Once the legends are made I'll add them, but hopefully that comes after some change to the color ramp They seem to be backward to me, which is interesting because it is similar to our bathymetry ramp. Maybe a single color light to dark (shallow to deep) would work better. Furthermore the three depth ramps may want to use the same min/max values, so they are immediately comparable.

Also, I think that consistency calls for the production wells and the domestic wells to be one service. We can put a subheader to distinguish them.

Also, a data frame description will need to be added for the right pane to populate.

Please file new issues for any specific changes.
